package com.zibi.mod.common.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

data class Dimensions(
  val zero: Dp = 0.dp,
  val xxSmallPadding: Dp = 1.dp,
  val xSmallPadding: Dp = 2.dp,
  val smallPadding: Dp = 4.dp,
  val mediumPadding: Dp = 8.dp,
  val xMediumPadding: Dp = 10.dp,
  val xxMediumPadding: Dp = 12.dp,
  val regularPadding: Dp = 16.dp,
  val mRegularPadding: Dp = 18.dp,
  val xRegularPadding: Dp = 20.dp,
  val largePadding: Dp = 21.dp,
  val xsLargePadding: Dp = 23.dp,
  val xLargePadding: Dp = 24.dp,
  val xmLargePadding: Dp = 25.dp,
  val xxLargePadding: Dp = 32.dp,
  val xxxLargePadding: Dp = 40.dp,
  val xxxLLargePadding: Dp = 64.dp,
  val inputFieldHeight: Dp = 56.dp,
  //TODO 04.05.2023 Tymczasowo dodana wysokość, do sprawdzenia przy tworzeniu MOB-5746
  val multilineInputFieldHeight: Dp = 96.dp,
  val smallCardWidth: Dp = 72.dp,
  val smallCardTextWidth: Dp = 106.dp,
  val smallCardCornerRadius: Dp = 16.dp,
  val statusIconSize: Dp = 14.dp,
  val statusWithoutIconSize: Dp = 10.dp,
  val smallButtonFabSize: Dp = 36.dp,
  val controllerSelectMinimumWidth: Dp = 96.dp,
  val topMenuIconSize: Dp = 40.dp,
  val topMenuIconXOffset: Dp = 12.dp,
  val controllerSwitchBoxHeight: Dp = 48.dp,
  val controllerButtonHeight: Dp = 40.dp,
  val dialogContentPadding: Dp = 36.dp,
  val dialogContentBottomPadding: Dp = 26.dp,
  val cardRadius: Dp = 12.dp,
  val cardMinimumHeight: Dp = 80.dp,
  val progressBarIndicatorRadius: Dp = 5.dp,
  val dropDownContentTopBarWidth: Dp = 117.dp,
  val dropDownContentTopBarHeight: Dp = 5.dp,
  val bottomSheetBottomPadding: Dp = 24.dp,
  val modalBarTopSheetPadding: Dp = 11.dp,
  val modalBarBottomSheetPadding: Dp = 42.dp,
  val minTooltipWidth: Dp = 160.dp,
  val maxTooltipWidth: Dp = 220.dp,
  val tooltipRadius: Dp = 6.dp,
  val tooltipArrowWidth: Dp = 10.dp,
  val tooltipArrowHeight: Dp = 8.dp,
  val tooltipArrowPadding: Dp = 20.dp,
  val documentCardWidth: Dp = 300.dp,
  val documentCardHeight: Dp = 200.dp,
  val documentCardElevation: Dp = 12.dp,
  val inputIconSize: Dp = 20.dp,
  val toastMainIconSize: Dp = 32.dp,
  val bottomTooltipRadius: Dp = 10.dp,
  val bottomTooltipPadding: Dp = 20.dp,
  val smallButtonSize: Dp = 32.dp,
  val modalBarHeight: Dp = 5.dp,
  val modalBarWidth: Dp = 134.dp,
  val smallButtonIconSize: Dp = 14.dp,
  val profileItemHeight: Dp = 72.dp,
  val documentCardLogoWidth: Dp = 126.dp,
  val documentCardLogoHeight: Dp = 92.dp,
  val legacyToolbarHeight: Dp = 56.dp,
  val bottomNavigationHeight: Dp = 80.dp,
  val errorImageSize: Dp = 20.dp,
  val localDocumentQrCodeIconSize: Dp = 60.dp,
  val localDocumentCardLogoSize: Dp = 80.dp,
  val localDocumentTopSpacerWidth: Dp = 180.dp,
  val localDocumentPhotoWidth: Dp = 130.dp,
  val localDocumentPhotoHeight: Dp = 180.dp,
  val localDocumentFlagWidth: Dp = 70.dp,
  val localDocumentFlagHeight: Dp = 45.dp,
  val localDocumentHologramSize: Dp = 42.dp,
  val localDocumentBottomBarHeight: Dp = 94.dp,
  val buttonNextHorizontalPadding: Dp = 30.dp,
  val buttonNextVerticalPadding: Dp = 24.dp,
  val powerOfAttorneyEmptyTabIconPadding: Dp = 116.dp,
  val dashboardPaymentCardWidth: Dp = 345.dp,
  val dashboardEmptyImageWidth: Dp = 280.dp,
  val dashboardEmptyImageHeight: Dp = 260.dp,
  val switchComponentWidth: Dp = 52.dp,
  val switchComponentHeight: Dp = 32.dp,
  val switchXComponentWidth: Dp = 68.dp,
  val switchXComponentHeight: Dp = 48.dp,
  val splashScreenVerticalLogoPadding: Dp = 10.dp,
  val splashScreenLogoTopPadding: Dp = 80.dp,
  val splashScreenFooterLogoHeight: Dp = 15.dp,
  val onboardingImageWidth: Dp = 280.dp,
  val onboardingImageHeight: Dp = 260.dp,
  val outroTopPadding: Dp = 182.dp,
  val outroTitleBottomPadding: Dp = 48.dp,
  val outroIconSize: Dp = 70.dp,
  val stepsIconSize: Dp = 24.dp,
  val loaderSize: Dp = 70.dp,
  val vehicleListItemIconSize: Dp = 74.dp,
  val vehicleListItemStatusPadding: Dp = 6.dp,
  val vehicleDetailsIconWidth: Dp = 137.dp,
  val pinInputBoxWidth: Dp = 40.dp,
  val pinInputBoxHeight: Dp = 48.dp,
)

internal val LocalDimension = staticCompositionLocalOf { Dimensions() }
